name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched for diff-cover

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest coverage diff-cover

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml  # Generate coverage.xml

      - name: Overall code coverage must be over 75%
        run: |
          coverage report --fail-under=75
          
      - name: New code coverage must be over 75%
        run: |
          diff-cover coverage.xml --compare-branch=${{ github.base_ref }} --fail-under=75
        

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
